Make sure that TOAST2 is installed before testing the framework

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -64,6 +64,10 @@ jobs:
         env:
           DUCC0_OPTIMIZATION: none
 
+      - name: Install TOAST2 (if possible)
+        # The “…|| true” trick avoids GitHub to detect any failure in the installation
+        run: pip install toast || true
+
       - name: Enable rich traceback
         continue-on-error: true
         run: |
